from collections.abc import AsyncIterator
from contextlib import AbstractAsyncContextManager
from typing import Protocol
from uuid import UUID

from tokenos.domain.models import Event, Reservation, Run, RunSpec


class LedgerTransaction(Protocol):
    async def get_run(self) -> Run: ...
    async def save_run(self, run: Run) -> None: ...
    async def get_reservation(self, reservation_id: UUID) -> Reservation | None: ...
    async def save_reservation(self, reservation: Reservation) -> None: ...
    async def append_event(self, event: Event) -> None: ...


class LedgerRepository(Protocol):
    async def create(self, spec: RunSpec) -> Run: ...
    async def read(self, run_id: UUID) -> Run: ...
    def transaction(self, run_id: UUID) -> AbstractAsyncContextManager[LedgerTransaction]: ...
    def events(self, run_id: UUID, after: int, limit: int) -> AsyncIterator[Event]: ...
